# Simple Recommendation

In [10]:
import re
import numpy as np
np.seterr(divide='ignore', invalid='ignore')

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

In [9]:
#Import and parse .dat file 

def parse(line):
    tempList=np.chararray((3, 1))
    #reg_match=_RegExLib(line)
    #parse each line and return the values split up
    sline = str(line.decode())
    #print(sline)
    tempList = (sline.split("::")) ##not storing the values properly
    return tempList

movies= np.chararray((3952, 1), itemsize = 100)
#movies = []
# First import the movie titles and store
with open('movies.dat','r',encoding = "ISO-8859-1") as m:
    ##lines = m.readlines()
    for line in m:
        list = parse(line.encode('utf-8').strip())
        #store in movies 
        #print(list[0])
        #print(list[1])
        movies[int(list[0])-1] = list[1].encode('utf-8')
        #movies.append(list[1])
        #print (movies[0].decode('utf-8'))
        #print(movies[1].decode('utf-8'))
    
        
ratings = np.zeros((6040,3952))
ratings[:]="0"
#Do the same for ratings
with open('ratings.dat','r',encoding = "ISO-8859-1") as r:
    ##lines = r.readlines()
    for line in r:
        list = parse(line.encode('utf-8').strip())
        #store in ratings 
        ratings[int(list[0])-1][int(list[1])-1] = int(list[2])
        
#User demographics is out of the scope of the project, will ignore 
#print(ratings)
#print(ratings[0][1192])

[[5. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [3. 0. 0. ... 0. 0. 0.]]


In [3]:
#Create similarity matrix - will be a square matrix of 6040x6040
#CORRELATION COEFFICIENT? calc. line for each person and see if positive or negative correlation with each other person
#Similarity will be abs value of that correlation coefficient

## or you can do 100 - the absolute value of the difference between the two people

similarity= np.zeros((6040,6040))

#print(np.shape(similarity))

similarity = np.corrcoef(ratings,(ratings))     
similarity = similarity[0:6040,0:6040]
#print((similarity))

In [4]:
#Make a binary rating matrix
binRatings = np.zeros((6040,3952))
binRatings[ratings>=1]=1
binRatings = np.transpose(binRatings)
#print(binRatings)

In [11]:
#Normalize and dot product
predRatings = np.array((6040,3952))
#for all rows in similarity

recommendations = np.chararray((6040,1),itemsize = 100)
s = 0
for i in range(0,6040):
    pRatings = (np.dot(similarity[i][:], ratings))
    #print(np.shape(pRatings))
    totals = (np.sum(np.abs(similarity[i][:]*binRatings[:][:]),axis = 1))
    #print(np.shape(totals))
    #print(pRatings)
    #print(totals)
    pRatings = np.divide(pRatings,totals)
    #np.abs(np.sum(similarity[0][:]*binRatings[:][:]))
    #predRatings[i][:] = pRatings
    
    #find max value for each person
    maxValIndex = np.argmax(pRatings)
    #print(maxValIndex)
    #find the corresponding movie title
    rTitle = movies[maxValIndex]
    #print(rTitle)
    #Store in a recommendations matrix
    recommendations[s] = rTitle.decode('utf-8')
    print(recommendations[s].decode('utf-8'))
    s = s+1

['Guardian Angel (1994)']
['Guardian Angel (1994)']
['Guardian Angel (1994)']
['Guardian Angel (1994)']
['Guardian Angel (1994)']
['Guardian Angel (1994)']


KeyboardInterrupt: 