# Simple Recommendation

In [101]:
import re
import numpy as np

In [102]:
#Import and parse .dat file 

def parse(line):
    tempList=np.chararray((3, 1))
    #reg_match=_RegExLib(line)
    #parse each line and return the values split up
    sline = "".join(map(chr, line))
    tempList = (sline.split("::")) ##not storing the values properly
    return tempList

#movies= np.chararray((3952, 1))
#movies[:]="0"
# First import the movie titles and store
#with open('movies.dat','r',encoding = "ISO-8859-1") as m:
    ##lines = m.readlines()
#    for line in m:
#        list = parse(line.encode('utf-8').strip())
        #store in movies 
#        movies[int(list[0])-1] = list[1]
        
ratings = np.zeros((6040,3952))
ratings[:]="0"
#Do the same for ratings
with open('ratings.dat','r',encoding = "ISO-8859-1") as r:
    ##lines = r.readlines()
    for line in r:
        list = parse(line.encode('utf-8').strip())
        #store in ratings 
        ratings[int(list[0])-1][int(list[1])-1] = int(list[2])
        
#User demographics is out of the scope of the project, will ignore 
#print(ratings)
#print(ratings[0][1192])

In [103]:
#Create similarity matrix - will be a square matrix of 6040x6040
#CORRELATION COEFFICIENT? calc. line for each person and see if positive or negative correlation with each other person
#Similarity will be abs value of that correlation coefficient

## or you can do 100 - the absolute value of the difference between the two people

similarity= np.zeros((6040,6040))

#print(np.shape(similarity))

similarity = np.corrcoef(ratings,(ratings))     
similarity = similarity[0:6040,0:6040]
#print('Hi')
#print((similarity))

In [104]:
#Make a binary rating matrix
binRatings = np.zeros((6040,3952))
binRatings[ratings>=1]=1
binRatings = np.transpose(binRatings)
#print(binRatings)

In [106]:
#Normalize and dot product
predRatings = np.array((6040,3952))
#for all rows in similarity

recommendations = np.chararray((6040,1))

for i in range(0,6040):
    pRatings = (np.dot(similarity[i][:], ratings))
    #print(np.shape(pRatings))
    totals = np.abs(np.sum(similarity[i][:]*binRatings[:][:],axis = 1))
    #print(np.shape(totals))
    print(pRatings)
    print(totals)
    pRatings = np.divide(pRatings,totals)
    #np.abs(np.sum(similarity[0][:]*binRatings[:][:]))
    #predRatings[i][:] = pRatings
    
    print(pRatings)
    print("Hello")
    #print(np.shape(pRatings))
    
    #find max value for each person
    
    #find the corresponding movie title
    
    #Store in a recommendations matrix

[1255.65782272  296.13530443  167.75655415 ...   22.9664621    13.93662846
  156.29201092]
[296.82061006  92.75722399  55.21909635 ...   6.0359436    3.49703898
  41.01258966]
[4.23035928 3.19258481 3.03801701 ... 3.80494975 3.98526541 3.81083009]
Hello


/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:13: RuntimeWarning: invalid value encountered in true_divide
  del sys.path[0]


[1330.07906792  369.21946937  224.27208639 ...   31.12437449   15.67677555
  219.71991226]
[320.3662101  116.30354186  75.38449104 ...   8.23507267   3.99346165
  57.81979359]
[4.1517458  3.17461931 2.97504279 ... 3.77948996 3.92561064 3.80008123]
Hello
[1288.41977715  351.01878149  199.62052059 ...   25.76374199   11.75678278
  167.28445824]
[308.91738925 110.0614918   66.31730176 ...   6.77417799   2.99789336
  44.33585426]
[4.17075834 3.18929696 3.01008206 ... 3.80322779 3.92168145 3.77311909]
Hello
[929.40823211 265.9176038  130.64229122 ...  21.07948797   9.26330448
 130.5769572 ]
[223.45183419  84.28790592  44.21189272 ...   5.48798286   2.3522136
  34.70063165]
[4.15932246 3.15487259 2.95491288 ... 3.84102657 3.93812215 3.76295621]
Hello
[1091.86275338  246.2191881   156.28607961 ...   30.24110779   21.01313446
  213.80600907]
[264.39480162  80.12366234  53.74406502 ...   8.1612586    5.41424615
  56.56059274]
[4.12966801 3.07298969 2.90796909 ... 3.70544658 3.88108222 3.7801232

KeyboardInterrupt: 